# Generated by Django 4.1.1 on 2022-09-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
